[package]
name = "graphic_handler"
version = "0.1.0"
edition = "2021"

[dependencies]
media_handler = { path = "../media_handler" }
env_logger = "0.8"
iced = "0.8.0"
iced_glow = "0.7.0"
iced_glutin = "0.7.0"
iced_winit = "0.8.0"
nalgebra = "0.32.2"
nalgebra-glm = "0.18.0"
rand = "0.8.5"
