[package]
name = "integration_opengl"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
env_logger = "0.8"
iced = "0.7.0"
iced_glow = "0.6.0"
iced_glutin = "0.6.0"
iced_winit = "0.7.0"
# custom crates